### ISSUE TITLE
Remove extra commas

### ISSUE THREAD

**Issue by Mamboleoo** [pierrestoffe/craft-instagram#1]
Because of the commas at the end of those lines I'm having errors with the plugin.

https://github.com/pierrestoffe/craft-instagram/blob/develop/src/services/FacebookApi.php#L200
https://github.com/pierrestoffe/craft-instagram/blob/develop/src/services/Media.php#L118
https://github.com/pierrestoffe/craft-instagram/blob/develop/src/services/InstagramApi.php#L196

**Comment by pierrestoffe** [comment]
Fixed in 1.0.1 (https://github.com/pierrestoffe/craft-instagram/releases/tag/1.0.1)
